// Deep discovery prompts — logged and used to auto-populate discovery board
export const CHAT_PROMPTS = [
  {
    id: 'p1',
    question: "What's your ideal Saturday morning?",
    category: 'Lifestyle',
    icon: '☀️',
    keywords: {
      coffee: { emoji: '☕', label: 'Morning Coffee', color: 'from-amber-600 to-orange-700' },
      sleep: { emoji: '😴', label: 'Sleeping In', color: 'from-indigo-600 to-purple-700' },
      run: { emoji: '🏃', label: 'Morning Run', color: 'from-green-500 to-teal-600' },
      yoga: { emoji: '🧘', label: 'Morning Yoga', color: 'from-teal-400 to-cyan-500' },
      cook: { emoji: '🥞', label: 'Cooking Breakfast', color: 'from-orange-400 to-red-500' },
      hike: { emoji: '🥾', label: 'Hiking', color: 'from-green-600 to-emerald-700' },
      read: { emoji: '📚', label: 'Reading', color: 'from-blue-400 to-indigo-500' },
      music: { emoji: '🎵', label: 'Listening to Music', color: 'from-purple-400 to-violet-500' },
      journal: { emoji: '📓', label: 'Journaling', color: 'from-amber-400 to-yellow-500' },
      nature: { emoji: '🌿', label: 'Being in Nature', color: 'from-green-400 to-lime-500' },
      market: { emoji: '🛍️', label: 'Farmers Market', color: 'from-orange-300 to-amber-400' },
    },
  },
  {
    id: 'p2',
    question: "Tea or coffee? Tell me your whole ritual around it.",
    category: 'Food & Drink',
    icon: '☕',
    keywords: {
      tea: { emoji: '🍵', label: 'Tea Lover', color: 'from-green-400 to-teal-500' },
      coffee: { emoji: '☕', label: 'Coffee Enthusiast', color: 'from-amber-700 to-orange-800' },
      matcha: { emoji: '🍵', label: 'Matcha Devotee', color: 'from-lime-400 to-green-500' },
      latte: { emoji: '☕', label: 'Latte Art', color: 'from-amber-400 to-orange-500' },
      herbal: { emoji: '🌿', label: 'Herbal Tea', color: 'from-green-500 to-emerald-600' },
      espresso: { emoji: '☕', label: 'Espresso', color: 'from-stone-600 to-gray-700' },
      chai: { emoji: '🍵', label: 'Chai Spice', color: 'from-orange-400 to-amber-500' },
      ceremony: { emoji: '🎋', label: 'Tea Ceremony', color: 'from-green-600 to-teal-700' },
    },
  },
  {
    id: 'p3',
    question: "What's a book, film, or documentary that genuinely changed how you see the world?",
    category: 'Culture & Ideas',
    icon: '📖',
    keywords: {
      book: { emoji: '📚', label: 'Avid Reader', color: 'from-blue-400 to-indigo-500' },
      film: { emoji: '🎬', label: 'Film Lover', color: 'from-red-500 to-rose-600' },
      movie: { emoji: '🎬', label: 'Movie Buff', color: 'from-red-400 to-rose-500' },
      documentary: { emoji: '🎞️', label: 'Documentary Watcher', color: 'from-slate-500 to-gray-600' },
      novel: { emoji: '📖', label: 'Novel Enthusiast', color: 'from-amber-400 to-yellow-500' },
      scifi: { emoji: '🚀', label: 'Sci-Fi Fan', color: 'from-slate-600 to-gray-700' },
      fantasy: { emoji: '🧙', label: 'Fantasy Worlds', color: 'from-violet-500 to-purple-600' },
      philosophy: { emoji: '🧠', label: 'Philosophy', color: 'from-blue-500 to-indigo-600' },
      memoir: { emoji: '📓', label: 'Memoir Reader', color: 'from-amber-500 to-orange-600' },
      graphic: { emoji: '🖼️', label: 'Graphic Novel Fan', color: 'from-pink-400 to-rose-500' },
    },
  },
  {
    id: 'p4',
    question: "If you could travel anywhere tomorrow, where — and what would you do there?",
    category: 'Travel',
    icon: '✈️',
    keywords: {
      japan: { emoji: '🗻', label: 'Japan Dreams', color: 'from-red-400 to-rose-500' },
      italy: { emoji: '🍕', label: 'Italy', color: 'from-green-400 to-red-500' },
      beach: { emoji: '🏖️', label: 'Beach Getaway', color: 'from-yellow-400 to-orange-500' },
      mountain: { emoji: '🏔️', label: 'Mountain Retreats', color: 'from-slate-500 to-gray-600' },
      paris: { emoji: '🗼', label: 'Paris', color: 'from-rose-400 to-pink-500' },
      city: { emoji: '🌆', label: 'City Explorer', color: 'from-indigo-500 to-purple-600' },
      island: { emoji: '🏝️', label: 'Island Life', color: 'from-teal-400 to-cyan-500' },
      forest: { emoji: '🌲', label: 'Forest Escapes', color: 'from-green-500 to-emerald-600' },
      space: { emoji: '🌌', label: 'Space Tourism', color: 'from-indigo-600 to-purple-700' },
      road: { emoji: '🛣️', label: 'Road Trips', color: 'from-orange-400 to-amber-500' },
      backpack: { emoji: '🎒', label: 'Backpacking', color: 'from-stone-500 to-amber-600' },
      solo: { emoji: '🧭', label: 'Solo Travel', color: 'from-sky-500 to-blue-600' },
    },
  },
  {
    id: 'p5',
    question: "What kind of music do you listen to when you need to feel something deeply?",
    category: 'Music',
    icon: '🎵',
    keywords: {
      jazz: { emoji: '🎷', label: 'Jazz', color: 'from-blue-500 to-indigo-600' },
      classical: { emoji: '🎻', label: 'Classical Music', color: 'from-amber-400 to-yellow-500' },
      hiphop: { emoji: '🎤', label: 'Hip-Hop', color: 'from-yellow-400 to-orange-500' },
      indie: { emoji: '🎸', label: 'Indie Music', color: 'from-violet-400 to-purple-500' },
      electronic: { emoji: '🎛️', label: 'Electronic', color: 'from-cyan-400 to-blue-500' },
      rock: { emoji: '🤘', label: 'Rock Music', color: 'from-red-500 to-rose-600' },
      rnb: { emoji: '🎙️', label: 'R&B / Soul', color: 'from-pink-400 to-rose-500' },
      lofi: { emoji: '🎵', label: 'Lo-fi Beats', color: 'from-teal-400 to-cyan-500' },
      pop: { emoji: '🌟', label: 'Pop Music', color: 'from-pink-300 to-rose-400' },
      ambient: { emoji: '🌊', label: 'Ambient / Chill', color: 'from-blue-400 to-teal-500' },
      folk: { emoji: '🪗', label: 'Folk Music', color: 'from-orange-400 to-amber-500' },
      metal: { emoji: '⚡', label: 'Metal', color: 'from-gray-700 to-slate-900' },
    },
  },
  {
    id: 'p6',
    question: "What's a skill or subject you could talk about for hours and never get bored?",
    category: 'Deep Interests',
    icon: '🔮',
    keywords: {
      history: { emoji: '📜', label: 'History Buff', color: 'from-amber-600 to-stone-700' },
      psychology: { emoji: '🧠', label: 'Psychology', color: 'from-purple-500 to-violet-600' },
      philosophy: { emoji: '🤔', label: 'Philosophy', color: 'from-blue-500 to-indigo-600' },
      astronomy: { emoji: '🔭', label: 'Astronomy', color: 'from-indigo-600 to-purple-700' },
      biology: { emoji: '🧬', label: 'Biology / Science', color: 'from-green-500 to-teal-600' },
      economics: { emoji: '📊', label: 'Economics', color: 'from-blue-400 to-cyan-500' },
      art: { emoji: '🎨', label: 'Art History', color: 'from-purple-400 to-pink-500' },
      language: { emoji: '🗣️', label: 'Linguistics', color: 'from-sky-400 to-blue-500' },
      design: { emoji: '✏️', label: 'Design Thinking', color: 'from-violet-400 to-purple-500' },
      climate: { emoji: '🌍', label: 'Climate & Nature', color: 'from-green-500 to-emerald-600' },
      politics: { emoji: '⚖️', label: 'Political Theory', color: 'from-slate-500 to-gray-600' },
      mythology: { emoji: '⚡', label: 'Mythology', color: 'from-yellow-500 to-amber-600' },
      cooking: { emoji: '👨‍🍳', label: 'Culinary Arts', color: 'from-orange-400 to-red-500' },
    },
  },
  {
    id: 'p7',
    question: "Night in or night out? Describe your perfect evening in detail.",
    category: 'Lifestyle',
    icon: '🌙',
    keywords: {
      homebody: { emoji: '🏠', label: 'Homebody', color: 'from-amber-400 to-orange-500' },
      social: { emoji: '🎉', label: 'Social Butterfly', color: 'from-pink-400 to-rose-500' },
      concert: { emoji: '🎸', label: 'Live Music', color: 'from-purple-400 to-violet-500' },
      cook: { emoji: '👨‍🍳', label: 'Cooking at Home', color: 'from-orange-400 to-red-500' },
      movie: { emoji: '🎬', label: 'Movie Nights', color: 'from-indigo-500 to-purple-600' },
      game: { emoji: '🎲', label: 'Game Nights', color: 'from-green-400 to-teal-500' },
      gallery: { emoji: '🖼️', label: 'Gallery Openings', color: 'from-violet-400 to-purple-500' },
      walk: { emoji: '🌃', label: 'Night Walks', color: 'from-indigo-600 to-blue-700' },
      star: { emoji: '🔭', label: 'Stargazing', color: 'from-indigo-500 to-purple-600' },
      rooftop: { emoji: '🌆', label: 'Rooftop Hangouts', color: 'from-orange-500 to-rose-500' },
      fire: { emoji: '🔥', label: 'Bonfire Nights', color: 'from-orange-600 to-red-700' },
    },
  },
  {
    id: 'p8',
    question: "What's something you're actively working on becoming better at — in life or craft?",
    category: 'Growth',
    icon: '🌱',
    keywords: {
      paint: { emoji: '🎨', label: 'Painting', color: 'from-purple-400 to-pink-500' },
      instrument: { emoji: '🎹', label: 'Playing Instrument', color: 'from-blue-400 to-indigo-500' },
      photo: { emoji: '📷', label: 'Photography', color: 'from-slate-400 to-gray-500' },
      write: { emoji: '✍️', label: 'Creative Writing', color: 'from-amber-400 to-yellow-500' },
      code: { emoji: '💻', label: 'Coding / Dev', color: 'from-blue-400 to-cyan-500' },
      dance: { emoji: '💃', label: 'Dancing', color: 'from-pink-400 to-rose-500' },
      pottery: { emoji: '🏺', label: 'Pottery', color: 'from-amber-500 to-orange-600' },
      film: { emoji: '🎬', label: 'Film Making', color: 'from-red-500 to-rose-600' },
      patience: { emoji: '🧘', label: 'Mindfulness', color: 'from-teal-400 to-cyan-500' },
      language: { emoji: '🗣️', label: 'Learning Language', color: 'from-sky-400 to-blue-500' },
      fitness: { emoji: '💪', label: 'Fitness Journey', color: 'from-green-500 to-teal-600' },
      public: { emoji: '🎤', label: 'Public Speaking', color: 'from-orange-400 to-amber-500' },
    },
  },
  {
    id: 'p9',
    question: "What's a value or belief you hold that most people might not expect from you?",
    category: 'Values',
    icon: '⚖️',
    keywords: {
      empathy: { emoji: '💗', label: 'Radical Empathy', color: 'from-rose-400 to-pink-500' },
      solitude: { emoji: '🤫', label: 'Loves Solitude', color: 'from-indigo-400 to-purple-500' },
      minimalism: { emoji: '🌊', label: 'Minimalist', color: 'from-slate-400 to-gray-600' },
      community: { emoji: '🤝', label: 'Community First', color: 'from-teal-400 to-cyan-500' },
      environment: { emoji: '🌍', label: 'Environmentalist', color: 'from-green-500 to-emerald-600' },
      spirituality: { emoji: '🕯️', label: 'Spiritual', color: 'from-purple-400 to-violet-500' },
      honesty: { emoji: '💎', label: 'Radical Honesty', color: 'from-blue-400 to-cyan-500' },
      freedom: { emoji: '🦅', label: 'Freedom Seeker', color: 'from-sky-500 to-blue-600' },
      justice: { emoji: '⚖️', label: 'Social Justice', color: 'from-orange-400 to-red-500' },
      kindness: { emoji: '☀️', label: 'Quiet Kindness', color: 'from-yellow-400 to-orange-500' },
      creativity: { emoji: '✨', label: 'Creates Daily', color: 'from-violet-400 to-pink-500' },
    },
  },
  {
    id: 'p10',
    question: "What's something small that genuinely makes your day better every time?",
    category: 'Joy',
    icon: '✨',
    keywords: {
      cat: { emoji: '🐱', label: 'Cat Person', color: 'from-orange-300 to-amber-400' },
      dog: { emoji: '🐶', label: 'Dog Person', color: 'from-yellow-400 to-amber-500' },
      plant: { emoji: '🌿', label: 'Plant Parent', color: 'from-green-400 to-emerald-500' },
      candle: { emoji: '🕯️', label: 'Candle Ritual', color: 'from-amber-400 to-orange-500' },
      sunrise: { emoji: '🌅', label: 'Sunrise Chaser', color: 'from-orange-400 to-rose-500' },
      window: { emoji: '🌧️', label: 'Rain & Windows', color: 'from-slate-400 to-blue-500' },
      cook: { emoji: '🥘', label: 'Cooking for Others', color: 'from-orange-400 to-red-500' },
      walk: { emoji: '🚶', label: 'Long Walks', color: 'from-green-400 to-teal-500' },
      song: { emoji: '🎵', label: 'That One Song', color: 'from-purple-400 to-violet-500' },
      notebook: { emoji: '📓', label: 'Filling Notebooks', color: 'from-amber-400 to-yellow-500' },
    },
  },
  {
    id: 'p11',
    question: "How do you recharge — do you need people around or time completely alone?",
    category: 'Energy',
    icon: '⚡',
    keywords: {
      introvert: { emoji: '🤫', label: 'Introvert', color: 'from-indigo-400 to-purple-500' },
      extrovert: { emoji: '🎉', label: 'Extrovert', color: 'from-pink-400 to-rose-500' },
      ambivert: { emoji: '⚖️', label: 'Ambivert', color: 'from-teal-400 to-blue-500' },
      alone: { emoji: '🌿', label: 'Recharges Alone', color: 'from-green-400 to-emerald-500' },
      people: { emoji: '👥', label: 'Energized by People', color: 'from-orange-400 to-rose-500' },
      nature: { emoji: '🌲', label: 'Nature Recharge', color: 'from-green-500 to-teal-600' },
      sleep: { emoji: '😴', label: 'Sleep is Sacred', color: 'from-indigo-600 to-purple-700' },
      exercise: { emoji: '🏃', label: 'Exercise to Recharge', color: 'from-green-500 to-teal-600' },
      create: { emoji: '🎨', label: 'Creates to Recharge', color: 'from-purple-400 to-pink-500' },
    },
  },
  {
    id: 'p12',
    question: "What's a niche obsession or hyperfixation you've fallen down a rabbit hole on?",
    category: 'Deep Dive',
    icon: '🕳️',
    keywords: {
      history: { emoji: '📜', label: 'History Rabbit Hole', color: 'from-amber-600 to-stone-700' },
      space: { emoji: '🌌', label: 'Space Nerd', color: 'from-indigo-600 to-purple-700' },
      true: { emoji: '🔍', label: 'True Crime', color: 'from-red-500 to-rose-600' },
      vintage: { emoji: '📼', label: 'Vintage / Retro', color: 'from-amber-400 to-orange-500' },
      maps: { emoji: '🗺️', label: 'Maps & Cartography', color: 'from-teal-400 to-cyan-500' },
      fungi: { emoji: '🍄', label: 'Mycology / Fungi', color: 'from-amber-500 to-stone-600' },
      urban: { emoji: '🏙️', label: 'Urban Exploration', color: 'from-slate-500 to-gray-700' },
      linguistics: { emoji: '🗣️', label: 'Linguistics', color: 'from-sky-400 to-blue-500' },
      folklore: { emoji: '🧙', label: 'Folklore & Myth', color: 'from-violet-500 to-purple-700' },
      economics: { emoji: '📊', label: 'Behavioral Economics', color: 'from-blue-400 to-cyan-500' },
      architecture: { emoji: '🏛️', label: 'Architecture', color: 'from-stone-400 to-gray-600' },
    },
  },
];

// Extract discovery items from message text using keyword matching
export function extractDiscoveries(text, prompt) {
  if (!text || !prompt) return [];
  const lower = text.toLowerCase();
  const found = [];
  if (!prompt.keywords) return found;
  for (const [key, item] of Object.entries(prompt.keywords)) {
    if (lower.includes(key)) found.push(item);
  }
  return found;
}

// Get a random prompt not yet used in this conversation
export function getNextPrompt(usedIds = []) {
  const unused = CHAT_PROMPTS.filter(p => !usedIds.includes(p.id));
  if (unused.length === 0) return null;
  return unused[Math.floor(Math.random() * unused.length)];
}
