// Mock data for the app

export const SUGGESTED_INTERESTS = [
  // Arts & Culture
  { label: 'Photography', emoji: '📷', category: 'Arts' },
  { label: 'Painting', emoji: '🎨', category: 'Arts' },
  { label: 'Music Production', emoji: '🎛️', category: 'Arts' },
  { label: 'Jazz', emoji: '🎷', category: 'Music' },
  { label: 'Classical Music', emoji: '🎻', category: 'Music' },
  { label: 'Hip-Hop', emoji: '🎤', category: 'Music' },
  { label: 'Indie Music', emoji: '🎸', category: 'Music' },
  { label: 'Film Making', emoji: '🎬', category: 'Arts' },
  { label: 'Drawing', emoji: '✏️', category: 'Arts' },
  { label: 'Sculpture', emoji: '🗿', category: 'Arts' },
  { label: 'Graphic Design', emoji: '💻', category: 'Arts' },
  { label: 'Poetry', emoji: '📝', category: 'Arts' },
  { label: 'Theater', emoji: '🎭', category: 'Arts' },

  // Food & Drink
  { label: 'Cooking', emoji: '👩‍🍳', category: 'Food' },
  { label: 'Baking', emoji: '🧁', category: 'Food' },
  { label: 'Coffee', emoji: '☕', category: 'Food' },
  { label: 'Sushi', emoji: '🍣', category: 'Food' },
  { label: 'Vegan Food', emoji: '🥗', category: 'Food' },
  { label: 'Street Food', emoji: '🌮', category: 'Food' },
  { label: 'Wine Tasting', emoji: '🍷', category: 'Food' },
  { label: 'Tea Culture', emoji: '🍵', category: 'Food' },
  { label: 'Pizza', emoji: '🍕', category: 'Food' },
  { label: 'Ramen', emoji: '🍜', category: 'Food' },

  // Tech
  { label: 'Coding', emoji: '💻', category: 'Tech' },
  { label: 'AI & Machine Learning', emoji: '🤖', category: 'Tech' },
  { label: 'Gaming', emoji: '🎮', category: 'Tech' },
  { label: 'Robotics', emoji: '🦾', category: 'Tech' },
  { label: 'VR/AR', emoji: '🥽', category: 'Tech' },
  { label: 'Cybersecurity', emoji: '🔐', category: 'Tech' },
  { label: 'Web Design', emoji: '🌐', category: 'Tech' },

  // Sports & Fitness
  { label: 'Running', emoji: '🏃', category: 'Sports' },
  { label: 'Yoga', emoji: '🧘', category: 'Sports' },
  { label: 'Rock Climbing', emoji: '🧗', category: 'Sports' },
  { label: 'Swimming', emoji: '🏊', category: 'Sports' },
  { label: 'Cycling', emoji: '🚴', category: 'Sports' },
  { label: 'Hiking', emoji: '🥾', category: 'Sports' },
  { label: 'Basketball', emoji: '🏀', category: 'Sports' },
  { label: 'Tennis', emoji: '🎾', category: 'Sports' },
  { label: 'Martial Arts', emoji: '🥋', category: 'Sports' },
  { label: 'Skateboarding', emoji: '🛹', category: 'Sports' },
  { label: 'Surfing', emoji: '🏄', category: 'Sports' },
  { label: 'Dancing', emoji: '💃', category: 'Sports' },

  // Nature & Travel
  { label: 'Travel', emoji: '✈️', category: 'Travel' },
  { label: 'Camping', emoji: '⛺', category: 'Travel' },
  { label: 'Stargazing', emoji: '🔭', category: 'Travel' },
  { label: 'Gardening', emoji: '🌱', category: 'Nature' },
  { label: 'Birdwatching', emoji: '🦜', category: 'Nature' },
  { label: 'Marine Life', emoji: '🐬', category: 'Nature' },
  { label: 'Astronomy', emoji: '🌌', category: 'Science' },

  // Learning & Mind
  { label: 'Reading', emoji: '📚', category: 'Learning' },
  { label: 'Philosophy', emoji: '🧠', category: 'Learning' },
  { label: 'Psychology', emoji: '🔮', category: 'Learning' },
  { label: 'History', emoji: '📜', category: 'Learning' },
  { label: 'Languages', emoji: '🗣️', category: 'Learning' },
  { label: 'Meditation', emoji: '🕯️', category: 'Wellness' },
  { label: 'Journaling', emoji: '📓', category: 'Wellness' },

  // Social
  { label: 'Board Games', emoji: '🎲', category: 'Social' },
  { label: 'Trivia Nights', emoji: '🏆', category: 'Social' },
  { label: 'Comedy', emoji: '😂', category: 'Social' },
  { label: 'Karaoke', emoji: '🎤', category: 'Social' },
  { label: 'Volunteering', emoji: '🤝', category: 'Social' },
  { label: 'Anime', emoji: '⛩️', category: 'Culture' },
  { label: 'Cosplay', emoji: '🦸', category: 'Culture' },
  { label: 'Astrology', emoji: '♈', category: 'Culture' },
  { label: 'Podcasts', emoji: '🎙️', category: 'Media' },
  { label: 'Documentaries', emoji: '🎞️', category: 'Media' },
  { label: 'True Crime', emoji: '🔍', category: 'Media' },
  { label: 'Sci-Fi', emoji: '🚀', category: 'Media' },
  { label: 'Fantasy', emoji: '🧙', category: 'Media' },
];

export const MOCK_USERS = [
  {
    id: 1,
    alias: 'NeonDreamer',
    avatar: 'ND',
    avatarColor: 'from-purple-500 to-pink-500',
    matchScore: 94,
    likes: ['Photography', 'Jazz', 'Coffee', 'Travel', 'Film Making'],
    dislikes: ['Early mornings', 'Loud crowds', 'Fast food'],
    interests: ['Philosophy', 'Indie Music', 'Stargazing'],
    visionBoard: [
      { emoji: '📷', label: 'Photography', color: 'from-violet-500 to-purple-600' },
      { emoji: '☕', label: 'Coffee', color: 'from-amber-600 to-orange-700' },
      { emoji: '🎷', label: 'Jazz', color: 'from-blue-500 to-indigo-600' },
      { emoji: '✈️', label: 'Travel', color: 'from-sky-500 to-blue-600' },
      { emoji: '🔭', label: 'Stargazing', color: 'from-indigo-600 to-purple-700' },
      { emoji: '🎬', label: 'Film Making', color: 'from-red-500 to-rose-600' },
    ],
  },
  {
    id: 2,
    alias: 'WildMosaic',
    avatar: 'WM',
    avatarColor: 'from-cyan-500 to-teal-500',
    matchScore: 87,
    likes: ['Rock Climbing', 'Cooking', 'Podcasts', 'Yoga', 'Reading'],
    dislikes: ['Negativity', 'Waste', 'Small talk'],
    interests: ['Psychology', 'Hiking', 'Meditation'],
    visionBoard: [
      { emoji: '🧗', label: 'Rock Climbing', color: 'from-stone-500 to-slate-600' },
      { emoji: '👩‍🍳', label: 'Cooking', color: 'from-orange-400 to-red-500' },
      { emoji: '🎙️', label: 'Podcasts', color: 'from-teal-500 to-cyan-600' },
      { emoji: '🧘', label: 'Yoga', color: 'from-green-400 to-teal-500' },
    ],
  },
  {
    id: 3,
    alias: 'PixelSage',
    avatar: 'PS',
    avatarColor: 'from-orange-500 to-pink-500',
    matchScore: 81,
    likes: ['Gaming', 'Anime', 'Coding', 'Sci-Fi', 'Board Games'],
    dislikes: ['Seriousness', 'No sense of humor', 'Slow internet'],
    interests: ['AI & Machine Learning', 'Fantasy', 'VR/AR'],
    visionBoard: [
      { emoji: '🎮', label: 'Gaming', color: 'from-green-500 to-emerald-600' },
      { emoji: '⛩️', label: 'Anime', color: 'from-red-500 to-pink-600' },
      { emoji: '💻', label: 'Coding', color: 'from-blue-400 to-indigo-500' },
      { emoji: '🚀', label: 'Sci-Fi', color: 'from-slate-600 to-gray-700' },
      { emoji: '🤖', label: 'AI', color: 'from-violet-500 to-purple-600' },
    ],
  },
  {
    id: 4,
    alias: 'SolarDrift',
    avatar: 'SD',
    avatarColor: 'from-yellow-400 to-orange-500',
    matchScore: 76,
    likes: ['Surfing', 'Music Production', 'Baking', 'Dancing', 'Travel'],
    dislikes: ['Winter', 'Complainers', 'Processed food'],
    interests: ['Hip-Hop', 'Street Food', 'Cycling'],
    visionBoard: [
      { emoji: '🏄', label: 'Surfing', color: 'from-sky-400 to-blue-500' },
      { emoji: '🎛️', label: 'Music Prod.', color: 'from-violet-400 to-pink-500' },
      { emoji: '🧁', label: 'Baking', color: 'from-rose-400 to-pink-500' },
      { emoji: '💃', label: 'Dancing', color: 'from-yellow-400 to-orange-500' },
    ],
  },
];

export const VISION_SEARCH_ITEMS = [
  // Places
  { emoji: '🗼', label: 'Paris', category: 'Places', color: 'from-rose-400 to-pink-500' },
  { emoji: '🏔️', label: 'Mountains', category: 'Places', color: 'from-slate-500 to-gray-600' },
  { emoji: '🏖️', label: 'Beach', category: 'Places', color: 'from-yellow-400 to-orange-500' },
  { emoji: '🌆', label: 'City Skyline', category: 'Places', color: 'from-indigo-500 to-purple-600' },
  { emoji: '🌿', label: 'Forest', category: 'Places', color: 'from-green-500 to-emerald-600' },
  { emoji: '🏜️', label: 'Desert', category: 'Places', color: 'from-amber-500 to-orange-600' },
  { emoji: '🌊', label: 'Ocean', category: 'Places', color: 'from-blue-400 to-cyan-500' },
  { emoji: '🗻', label: 'Japan', category: 'Places', color: 'from-red-400 to-rose-500' },
  { emoji: '🌉', label: 'San Francisco', category: 'Places', color: 'from-orange-400 to-red-500' },
  { emoji: '🏝️', label: 'Tropical Island', category: 'Places', color: 'from-teal-400 to-cyan-500' },
  { emoji: '🌋', label: 'Volcano', category: 'Places', color: 'from-red-600 to-orange-700' },
  { emoji: '🌃', label: 'Night City', category: 'Places', color: 'from-indigo-600 to-blue-700' },

  // Food
  { emoji: '🍣', label: 'Sushi', category: 'Food', color: 'from-pink-400 to-rose-500' },
  { emoji: '🍕', label: 'Pizza', category: 'Food', color: 'from-orange-400 to-red-500' },
  { emoji: '☕', label: 'Coffee', category: 'Food', color: 'from-amber-600 to-orange-700' },
  { emoji: '🧁', label: 'Cupcakes', category: 'Food', color: 'from-pink-400 to-purple-500' },
  { emoji: '🍜', label: 'Ramen', category: 'Food', color: 'from-red-400 to-orange-500' },
  { emoji: '🥑', label: 'Avocado', category: 'Food', color: 'from-green-400 to-lime-500' },
  { emoji: '🍵', label: 'Matcha Tea', category: 'Food', color: 'from-green-500 to-teal-600' },
  { emoji: '🍫', label: 'Chocolate', category: 'Food', color: 'from-amber-700 to-brown-800' },
  { emoji: '🌮', label: 'Tacos', category: 'Food', color: 'from-yellow-400 to-orange-500' },

  // Activities
  { emoji: '🧗', label: 'Rock Climbing', category: 'Activities', color: 'from-stone-500 to-slate-600' },
  { emoji: '🎨', label: 'Painting', category: 'Activities', color: 'from-purple-400 to-pink-500' },
  { emoji: '🎮', label: 'Gaming', category: 'Activities', color: 'from-green-500 to-emerald-600' },
  { emoji: '📚', label: 'Reading', category: 'Activities', color: 'from-blue-400 to-indigo-500' },
  { emoji: '🎸', label: 'Guitar', category: 'Activities', color: 'from-orange-400 to-red-500' },
  { emoji: '🧘', label: 'Yoga', category: 'Activities', color: 'from-teal-400 to-cyan-500' },
  { emoji: '🏄', label: 'Surfing', category: 'Activities', color: 'from-sky-400 to-blue-500' },
  { emoji: '💃', label: 'Dancing', category: 'Activities', color: 'from-pink-400 to-rose-500' },
  { emoji: '🎭', label: 'Theater', category: 'Activities', color: 'from-violet-400 to-purple-500' },
  { emoji: '📷', label: 'Photography', category: 'Activities', color: 'from-slate-400 to-gray-500' },
  { emoji: '🚴', label: 'Cycling', category: 'Activities', color: 'from-lime-400 to-green-500' },
  { emoji: '🏊', label: 'Swimming', category: 'Activities', color: 'from-blue-400 to-cyan-500' },
  { emoji: '🎯', label: 'Archery', category: 'Activities', color: 'from-red-400 to-rose-500' },
  { emoji: '🛹', label: 'Skateboarding', category: 'Activities', color: 'from-gray-500 to-slate-600' },

  // Aesthetics & Vibes
  { emoji: '🌙', label: 'Night Owl', category: 'Vibes', color: 'from-indigo-600 to-purple-700' },
  { emoji: '☀️', label: 'Morning Person', category: 'Vibes', color: 'from-yellow-400 to-orange-500' },
  { emoji: '🌸', label: 'Cherry Blossoms', category: 'Vibes', color: 'from-pink-300 to-rose-400' },
  { emoji: '🌌', label: 'Galaxy', category: 'Vibes', color: 'from-indigo-500 to-purple-600' },
  { emoji: '🕯️', label: 'Candlelit', category: 'Vibes', color: 'from-amber-400 to-orange-500' },
  { emoji: '🌊', label: 'Minimalist', category: 'Vibes', color: 'from-slate-400 to-gray-500' },
  { emoji: '🎪', label: 'Colorful Chaos', category: 'Vibes', color: 'from-rainbow-400 to-pink-500' },
  { emoji: '🔮', label: 'Mystical', category: 'Vibes', color: 'from-purple-500 to-violet-600' },
  { emoji: '🌿', label: 'Cottagecore', category: 'Vibes', color: 'from-green-400 to-emerald-500' },
  { emoji: '🖤', label: 'Dark Aesthetic', category: 'Vibes', color: 'from-gray-700 to-slate-800' },
  { emoji: '🎠', label: 'Whimsical', category: 'Vibes', color: 'from-pink-400 to-purple-500' },

  // Animals
  { emoji: '🐱', label: 'Cat Person', category: 'Animals', color: 'from-orange-300 to-amber-400' },
  { emoji: '🐶', label: 'Dog Person', category: 'Animals', color: 'from-yellow-400 to-amber-500' },
  { emoji: '🐺', label: 'Wolf', category: 'Animals', color: 'from-gray-500 to-slate-600' },
  { emoji: '🦋', label: 'Butterflies', category: 'Animals', color: 'from-blue-300 to-violet-400' },
  { emoji: '🐧', label: 'Penguins', category: 'Animals', color: 'from-slate-500 to-gray-600' },
  { emoji: '🦊', label: 'Fox', category: 'Animals', color: 'from-orange-400 to-red-500' },
  { emoji: '🐉', label: 'Dragon', category: 'Animals', color: 'from-emerald-500 to-green-600' },

  // Music
  { emoji: '🎷', label: 'Jazz', category: 'Music', color: 'from-blue-500 to-indigo-600' },
  { emoji: '🎤', label: 'Hip-Hop', category: 'Music', color: 'from-yellow-400 to-orange-500' },
  { emoji: '🎻', label: 'Classical', category: 'Music', color: 'from-amber-400 to-yellow-500' },
  { emoji: '🎸', label: 'Rock', category: 'Music', color: 'from-red-500 to-rose-600' },
  { emoji: '🎹', label: 'Piano', category: 'Music', color: 'from-slate-600 to-gray-700' },
  { emoji: '🥁', label: 'Drums', category: 'Music', color: 'from-red-400 to-orange-500' },
  { emoji: '🎛️', label: 'Electronic', category: 'Music', color: 'from-violet-500 to-purple-600' },
  { emoji: '🎵', label: 'Lo-fi', category: 'Music', color: 'from-teal-400 to-cyan-500' },

  // Tech
  { emoji: '🤖', label: 'AI', category: 'Tech', color: 'from-violet-500 to-purple-600' },
  { emoji: '💻', label: 'Coding', category: 'Tech', color: 'from-blue-400 to-indigo-500' },
  { emoji: '🥽', label: 'VR/AR', category: 'Tech', color: 'from-cyan-400 to-teal-500' },
  { emoji: '🚀', label: 'Space Tech', category: 'Tech', color: 'from-slate-600 to-gray-700' },
  { emoji: '🎮', label: 'Esports', category: 'Tech', color: 'from-green-500 to-emerald-600' },
];
